# Generated by Django 3.1.5 on 2021-04-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20210411_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(default='', upload_to='pics')),
                ('desc', models.CharField(default='', max_length=10000)),
                ('discount', models.IntegerField(default='40')),
                ('actualprice', models.IntegerField(default='6000')),
                ('regularprice', models.IntegerField(default='10000')),
            ],
        ),
    ]
