# Generated by Django 3.2 on 2021-04-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='', max_length=10000)),
                ('price', models.IntegerField(default='0', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateTimeField(auto_now_add=True)),
                ('destination', models.CharField(default='', max_length=10000)),
                ('member', models.IntegerField(default='1', max_length=10000)),
                ('checkin', models.IntegerField(default='1', max_length=10000)),
                ('totalamount', models.IntegerField(default='0', max_length=10000)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(default='', max_length=10000)),
                ('address', models.CharField(default='', max_length=10000)),
                ('city', models.CharField(default='', max_length=10000)),
                ('pincode', models.IntegerField(default='', max_length=10000)),
                ('state', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
