# Generated by Django 3.2 on 2021-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_menu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkin',
        ),
        migrations.AddField(
            model_name='order',
            name='checkin_day',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkin_month',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalamount',
            field=models.IntegerField(default='0'),
        ),
    ]
