# Generated by Django 3.2 on 2021-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_menu_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='order',
            name='Address2',
            field=models.CharField(default='', max_length=400),
        ),
    ]
