# Generated by Django 3.2 on 2021-04-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20210418_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkin_day',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkin_month',
            field=models.IntegerField(default='1'),
        ),
    ]
