# Generated by Django 3.2 on 2021-04-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20210418_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='checkin',
            new_name='checkin_day',
        ),
        migrations.AddField(
            model_name='order',
            name='checkin_month',
            field=models.IntegerField(default='1'),
        ),
    ]
