# Generated by Django 3.2 on 2021-04-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20210418_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bookingdate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='checkin_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='checkin_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='member',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totalamount',
        ),
    ]
